CREATE DATABASE mx_track_manager;

CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bikes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    brand VARCHAR(255),
    model VARCHAR(255),
    year YEAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sessions (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bike_id INT UNSIGNED NOT NULL,
    date DATE NOT NULL,
    track VARCHAR(100) NOT NULL,
    weather VARCHAR(50),
    feeling TINYINT,
    hours_logged DECIMAL(4,2),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bike_id) REFERENCES bikes(id) ON DELETE CASCADE
);

CREATE TABLE maintenance (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bike_id INT UNSIGNED NOT NULL,
    task_description VARCHAR(150) NOT NULL,
    hour_threshold DECIMAL(6,2),
    last_service_hours DECIMAL(6,2),
    service_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bike_id) REFERENCES bikes(id) ON DELETE CASCADE
);